---
title: "Simulation results"
format: html
---

```{r}
#| include: false

library(tidyverse)
library(kableExtra)
source('~/work/R_files/summary.R')
```

# Boxplots of estimated correlation coefficients

100 simulations were run for each setting.

::: {.panel-tabset}

## Weak signal, weak intra

```{r}
weak_weak_dir <- file.path("simulation-output", "weak-signal-weak-intra")
weak_weak_dir <- paste0("~/work/", weak_weak_dir)
rho_true <- read_csv(
    file.path(weak_weak_dir, "rho_true.csv"), show_col_types = FALSE)
weak_weak <- readRDS(file.path(weak_weak_dir, "results.rds"))
boxplot_3_region(weak_weak, rho_true)
```

## Weak signal, strong intra

```{r}
weak_strong_dir <- file.path("simulation-output", "weak-signal-strong-intra")
weak_strong_dir <- paste0("~/work/", weak_strong_dir)
rho_true <- read_csv(
    file.path(weak_strong_dir, "rho_true.csv"), show_col_types = FALSE)
weak_strong <- readRDS(file.path(weak_strong_dir, "results.rds"))
boxplot_3_region(weak_strong, rho_true)
```

## Medium signal, weak intra

```{r}
medium_weak_dir <- file.path("simulation-output", "med-signal-weak-intra")
medium_weak_dir <- paste0("~/work/", medium_weak_dir)
rho_true <- read_csv(
    file.path(medium_weak_dir, "rho_true.csv"), show_col_types = FALSE)
medium_weak <- readRDS(file.path(medium_weak_dir, "results.rds"))
boxplot_3_region(medium_weak, rho_true)
```

## Medium signal, strong intra

```{r}
medium_strong_dir <- file.path("simulation-output", "med-signal-strong-intra")
medium_strong_dir <- paste0("~/work/", medium_strong_dir)
rho_true <- read_csv(
    file.path(medium_strong_dir, "rho_true.csv"), show_col_types = FALSE)
medium_strong <- readRDS(file.path(medium_strong_dir, "results.rds"))
boxplot_3_region(medium_strong, rho_true)
```

## Strong signal, weak intra

```{r}
strong_weak_dir <- file.path("simulation-output", "strong-signal-weak-intra")
strong_weak_dir <- paste0("~/work/", strong_weak_dir)
rho_true <- read_csv(
    file.path(strong_weak_dir, "rho_true.csv"), show_col_types = FALSE)
strong_weak <- readRDS(file.path(strong_weak_dir, "results.rds"))
boxplot_3_region(strong_weak, rho_true)
```

## Strong signal, strong intra

```{r}
strong_strong_dir <- file.path("simulation-output", "strong-signal-strong-intra")
strong_strong_dir <- paste0("~/work/", strong_strong_dir)
rho_true <- read_csv(
    file.path(strong_strong_dir, "rho_true.csv"), show_col_types = FALSE)
strong_strong <- readRDS(file.path(strong_strong_dir, "results.rds"))
boxplot_3_region(strong_strong, rho_true)
```

:::

# Boxplots grouped by region

::: {.panel-tabset}

## Regions 1 and 2

```{r}
#| echo: false

wwr12 <- as.data.frame(weak_weak$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("weak"))

wsr12 <- as.data.frame(weak_strong$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("strong"))

mwr12 <- as.data.frame(medium_weak$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("weak"))

msr12 <- as.data.frame(medium_strong$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("strong"))

swr12 <- as.data.frame(strong_weak$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("weak"))

ssr12 <- as.data.frame(strong_strong$r12) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("strong"))

r12df <- rbind(wwr12, wsr12, mwr12, msr12, swr12, ssr12)

levels(r12df$signal) <- c(
    weak = expression(k[eta] == 0.5),
    med = expression(k[eta] == 1),
    strong = expression(k[eta] == 1.5))

levels(r12df$intra) <- c(
    weak = expression(phi[gamma] == 1),
    strong = expression(phi[gamma] == 0.25))

ggplot(r12df,
  aes(y = corr, x = corrtype, fill = corrtype)) +
  geom_boxplot(show.legend = FALSE) +
  geom_hline(
    yintercept = rho_true[[1]], color="red", linetype='dashed') +
  xlab(NULL) +
  ylab(expression(rho)) +
  facet_grid(signal ~ intra, labeller = label_parsed) +
  ylim(-1, 1) +
  theme_bw() +
  scale_fill_brewer(palette="Set2")
```

## Regions 1 and 3

```{r}
#| echo: false

wwr13 <- as.data.frame(weak_weak$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("weak"))

wsr13 <- as.data.frame(weak_strong$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("strong"))

mwr13 <- as.data.frame(medium_weak$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("weak"))

msr13 <- as.data.frame(medium_strong$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("strong"))

swr13 <- as.data.frame(strong_weak$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("weak"))

ssr13 <- as.data.frame(strong_strong$r13) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("strong"))

r13df <- rbind(wwr13, wsr13, mwr13, msr13, swr13, ssr13)

levels(r13df$signal) <- c(
    weak = expression(k[eta] == 0.5),
    med = expression(k[eta] == 1),
    strong = expression(k[eta] == 1.5))

levels(r13df$intra) <- c(
    weak = expression(phi[gamma] == 1),
    strong = expression(phi[gamma] == 0.25))

ggplot(r13df,
    aes(y = corr, x = corrtype, fill = corrtype)) +
  geom_boxplot(show.legend = FALSE) +
    geom_hline(
        yintercept = rho_true[[2]], color="red", linetype='dashed') +
    xlab(NULL) +
    ylab(expression(rho)) +
    facet_grid(signal ~ intra, labeller = label_parsed) +
    ylim(-1, 1) +
    theme_bw() +
    scale_fill_brewer(palette="Set2")
```

## Regions 2 and 3

```{r}
#| echo: false

wwr23 <- as.data.frame(weak_weak$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("weak"))

wsr23 <- as.data.frame(weak_strong$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("weak"), intra = factor("strong"))

mwr23 <- as.data.frame(medium_weak$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("weak"))

msr23 <- as.data.frame(medium_strong$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("medium"), intra = factor("strong"))

swr23 <- as.data.frame(strong_weak$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("weak"))

ssr23 <- as.data.frame(strong_strong$r23) |>
    select(-asympvar) |>
    pivot_longer(cols = c("Intra", "CA", "bCA", "qfunc"),
                 names_to = "corrtype", values_to = "corr") |>
    mutate(corrtype = factor(corrtype), signal = factor("strong"), intra = factor("strong"))

r23df <- rbind(wwr23, wsr23, mwr23, msr23, swr23, ssr23)

levels(r23df$signal) <- c(
    weak = expression(k[eta] == 0.5),
    med = expression(k[eta] == 1),
    strong = expression(k[eta] == 1.5))

levels(r23df$intra) <- c(
    weak = expression(phi[gamma] == 1),
    strong = expression(phi[gamma] == 0.25))

ggplot(r23df,
    aes(y = corr, x = corrtype, fill = corrtype)) +
    geom_boxplot(show.legend = FALSE) +
    geom_hline(
        yintercept = rho_true[[3]], color="red", linetype='dashed') +
    xlab(NULL) +
    ylab(expression(rho)) +
    facet_grid(signal ~ intra, labeller = label_parsed) +
    ylim(-1, 1) +
    theme_bw() +
    scale_fill_brewer(palette="Set2")
```


:::
