---
title: "New QfunC Package Function"
format: html
---

## Load libraries and data

We load simulated data on three regions.
```{r}
library(qfuncMM)
library(readr)

# Reshape data into a matrix with n_timept rows and n_voxel columns
reshape_signal <- function(signal) {
  n_timept <- 60
  n_voxel <- 50
  return(matrix(signal, nrow = n_timept, ncol = n_voxel))
}

setting <- "weak-signal-weak-intra"
voxel_coords <- readRDS(
  file.path("../simulation-data", setting, "voxel_coords.rds"))
sim <- readRDS(file.path("../simulation-data", setting, "sim-data.rds"))[[1]]
region_list <- lapply(sim, reshape_signal)
```

Our function `qfunc` requires two main inputs:
1. `region_list`: a list of matrices, each matrix is a time series of voxels in a region
2. `voxel_coords`: a matrix of voxel coordinates, each row is a voxel

```{r}
str(region_list)
str(voxel_coords)
head(voxel_coords[[1]]) # spatial coordinates of first few voxels
```

## Run the analysis


The entire analysis is done in a single function call:
```{r}
result <- qfuncmm(region_list, voxel_coords, n_basis = 45)
str(result)
```

The estimated correlations from REML:
```{r}
result$cor
```